export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
